### ISSUE TITLE
Adding Launchers in gnome 3?

### ISSUE THREAD

**Issue by bollwyvl** [newville/pyshortcuts#1]
Thanks for this!

Gnome 3 doesn't really have a move-stuff-around desktop. The `~/Desktop` is still created, it seems, but the default file browser doesn't render `.desktop` applications as anything other than text files, and clicking them just opens them in your text editor.

However, putting `.desktop` files in `~/.local/share/applications/` will make them accessible to the launcher under the super key or hot corner. I was sceptical at first, but it's grown on me.

In some experiments, I've been successful in moving the generated shortcuts there, and they work fine, but as it becomes the default on more distros, it might be nice to offer detection of this. Happy to do some more research/PR if interested!

**Comment by newville** [comment]
@bollwyvl  Thanks -- that's a good point.   

For sure, the best location for the `.desktop` files on Linux seems to depend strongly on the window manager.   If there is a reliable way to detect (or maybe have the end user specify?) where the best place is, I would certainly have no objections to using that.  I'm definitely open to suggestions and PRs.

**Comment by bollwyvl** [comment]
yeah, no doubt this would take a lot of data and testing! Here's some random [googling](https://unix.stackexchange.com/questions/116539/how-to-detect-the-desktop-environment-in-a-bash-script) specifically this [comment](https://unix.stackexchange.com/a/120227) that could likely be adapted. I guess it depends on how sure we'd want to be!

**Comment by newville** [comment]
@bollwyvl What if we just put a `.desktop` file in `$HOME/Desktop` if it exists, and also put one in `$HOME/.local/share/applications` if that exists?  The desktop files are tiny and owned by the end-user, so I don't see any harm in having a couple copies.  And, I believe that for KDE, LXQt, etc that the `$HOME/.local/share/applications` location will then be available (or at least findable) from the "Start Menu".

**Comment by bollwyvl** [comment]
I like that plan! Being able to hit 80% with two locations is nice.

**Comment by newville** [comment]
Closing, as I think this is addressed.
