### ISSUE TITLE
No icon on shortcuts!

### ISSUE THREAD

**Issue by Acmpo6ou** [newville/pyshortcuts#26]
Hello!
I am using pyshortcuts on Linux. Here is code of my application which must create shortcut:
```python
make_shortcut(
    name='PyQtAccounts',
    script=cwd + '/run.sh',
    description='Simple account database manager.',
    icon=cwd+'/img/icon.svg',
    terminal=False,
    desktop=desktop,
    startmenu=startmenu,
    executable='/bin/bash'
)
```
Everything is alright the shortcut appears in menu and desktop but there is no icon.
I looked on shortcut code, here it is:
```
[Desktop Entry]
Name=PyQtAccounts
Type=Application
Comment=Simple account database manager.
Terminal=false
Icon=/home/python/Downloads/PyQtAccounts/img/icon.svg.ico
Exec=/bin/bash /home/python/Downloads/PyQtAccounts/run.sh 
```
If you look at this line:
`Icon=/home/python/Downloads/PyQtAccounts/img/icon.svg.ico`
and at this line in my code:
```python
...
icon=cwd+'/img/icon.svg',
...
```
You'll see that i wanted the **icon.svg** not **icon.svg.ico**.
Can you fix this issue and make pyshortcuts to not add .ico for my icon path, please?

**Comment by newville** [comment]
@Acmpo6ou sorry for the trouble.  yes, currently the code requires that linux icons are '.ico' files.   Are '.svg' files generally usable as icons on linux?  

If altering the resulting .desktop file is not sufficient, I would recommend trying to change the code to search if the user-supplied icon file exists (without appending '.ico'), and then checking if appending '.ico' and then '.svg' (and perhaps '.png') makes a filename that exists.   Does that make sense?  If you're up for it, I'd suggest making sure a  PR.

**Comment by Acmpo6ou** [comment]
Hello!
Yes .svg .png . gif .jpeg and so on are usable.
Well, I will think about fixing issue, just never did something like this before.
PS: Sorry, I speak English a little.

**Comment by Acmpo6ou** [comment]
@newville thanks for merging. I understand that I, may be, fixed it not exactly like you wanted me to. It's because I think that in such cases, when the path to icon is incorrect we might just need to throw an exception, because in that way programmer will understand what exactly wrong he did.
If you know what I mean. Because I, may be, not good at English enough to explain that.

**Comment by GaetanoGeck** [comment]
First off, thanks for _pyshortcuts_! I'm considering to use it in one of my projects and I would like to use icons in PNG format. With version 1.7.2, this seems to be possible now but not with version 1.7.1, which brings me to my question: do you intend to publish version 1.7.2. on PyPI in the near future?

**Comment by newville** [comment]
@GaetanoGeck yes. that is a good point - v 1.7.2 is not on PyPI.  Actually, there are a couple more changes since then, so I'll try to get 1.7.3 out this week and pushed to pypi.

**Comment by GaetanoGeck** [comment]
Thanks very much!

**Comment by newville** [comment]
@GaetanoGeck Pyshortcuts 1.8 is now on PyPI and should fix this.

**Comment by GaetanoGeck** [comment]
@newville Thanks for doing it so quickly and thanks for the notification.

**Comment by newville** [comment]
@GaetanoGeck cheers!
