### ISSUE TITLE
Work path missing

### ISSUE THREAD

**Issue by jrphysics** [newville/pyshortcuts#31]
Hello!

The work path (aka. working directory) is not a parameter of make_shortcut. Would it be possible to include it?

Thanks!

**Comment by newville** [comment]
@jrphysics sure, that's a fine idea.  It would be clear how to do that for Windows.  For MacOS that could just go into the shell script called by the mini-App.  I'm not sure if there is a simple way to do that for Linux .desktop files: maybe set "Path" to the working folder and then make sure that the "Exec" value is a full pat. That's untested.

Anyway, sure.  A pull request for that would be welcome!

**Comment by jrphysics** [comment]
Indeed for Linux it would also work just as you described, that's what I was doing before coming across pyshortcuts.

Would a partial PR help? Can do for Linux and maybe Windows, but no idea about MacOS.

**Comment by newville** [comment]
should be fixed.
