### ISSUE TITLE
cannot bring up pyshortcut GUI form

### ISSUE THREAD

**Issue by shift838** [newville/pyshortcuts#33]
I have tried this on both windows and macOS with the same results.

I have installed the pyshortcuts module and when executing 'pyshortcut -w' or 'pyshortcut --wxgui' I get the below error and the GUI window does not show up.

`pyshortcut: must provide one script.  try 'pyshortcuts -h'

`

**Comment by newville** [comment]
@shift838 is wxpython installed?

**Comment by shift838** [comment]
I checked and it was not installed.  I installed it on my MacOS and when executed I now get:

Traceback (most recent call last):
  File "/usr/local/bin/pyshortcut", line 11, in <module>
    load_entry_point('pyshortcuts==1.7.1', 'console_scripts', 'pyshortcut')()
  File "/usr/local/lib/python3.7/site-packages/pyshortcuts/__init__.py", line 99, in shortcut_cli
    ShortcutFrame().Show(True)
  File "/usr/local/lib/python3.7/site-packages/pyshortcuts/wxgui.py", line 160, in __init__
    fsizer.Add(panel, 0, wx.ALIGN_LEFT|wx.ALIGN_CENTER|wx.EXPAND)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at /Users/robind/projects/bb2/dist-osx-py37/build/ext/wxWidgets/src/common/sizer.cpp(2089) in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

**Comment by newville** [comment]
@shift838 ah, sorry for that.  Code that worked (but was apparently ignored) with wxPython 4.0.* fails with 4.1.  I've been seeing that in many wxPython-based projects but forgot to fix this one.

I will fix it and push to the master branch soon.  For a quick fix on your system, just remove that `wx.EXPAND` so that lines reads:

```
fsizer.Add(panel, 0, wx.ALIGN_LEFT|wx.ALIGN_CENTER)
```
