### ISSUE TITLE
is there a way to set working directory?

### ISSUE THREAD

**Issue by shift838** [newville/pyshortcuts#34]
Is there a way to set working directory for the shortcut/alias?

my command I am using to create the shortcut is:

make_shortcut("/Users/shift838/ooeyguiv4/output/ooeygui/ooeygui", name = "OoeyGUI", icon = "/Users/shift838/ooeyguiv4/output/ooeygui/images/og1.icns")

this creates the shortcut on the macOS desktop with no issue.  but.. when executing it since I have it is looking for supporting files in the Desktop folder instead of the ooeygui application folder.

**Comment by newville** [comment]
@shift838 If I understand correctly, you're asking to set the working directory that the script runs in (not the folder that the shortcut lives in).

If that is correct:  the code does not currently support that but could almost certainly be altered to do so.  For sure, "starting directory" is supported for Windows links (we currently set it to "HOME").  Linux desktop files have a PATH attribute, which we don't set, but I think must default to "HOME".  For macOS, we run a bash script and could add "move to selected working folder". 
  
So, I think that would be a fine thing to add.   Do you feel up to trying to make those changes?

**Comment by newville** [comment]
should be fixed now.
