### ISSUE TITLE
Only one '.' allowed in shortcut name

### ISSUE THREAD

**Issue by jacobwilliams** [newville/pyshortcuts#39]
I notice in `fix_filename` it only allows one `.` to be in the name. Was wondering on what platform this is a problem? It would be nice to be able to put a version number like `1.3.2` in the shortcut name. It's OK on Windows.

**Comment by newville** [comment]
@jacobwilliams  I guess that "no more than one dot" is a pretty common -- but outdated -- restriction.  Are you willing to mae a PR?

**Comment by jacobwilliams** [comment]
Let me know if that's what you had in mind. I left the old code there just in case.
