### ISSUE TITLE
pyshortcuts-1.8.2 on pypi has indentations errors in pyshortcuts.base

### ISSUE THREAD

**Issue by shakfu** [newville/pyshortcuts#47]
The current pyshortcuts pypi release 1.8.2 contains a module `pyshortcuts/base.py` which contains syntax / indentation errors. 

May I suggest it's taken down and updated asap.

**Comment by newville** [comment]
@shakfu Thanks!  I've pushed tarball and wheels for 1.8.3 to PyPI which should fix this problem.

**Comment by shakfu** [comment]
My pleasure. Thanks for the quick fix.
