### ISSUE TITLE
option to enable "-m" argument

### ISSUE THREAD

**Issue by lamaresh** [newville/pyshortcuts#49]
Would be possible to add an argument in the make_shortcut function to add the "-m" argument to the python executable? in that case the script string should be taken without adding any path before it and this would enable the possibility to execute module as scripts when a package was installed with an entry point

thank you

**Comment by newville** [comment]
@lamaresh Sorry for being dense, but I am not sure I understand.  Do you mean you want to be able to do something like 

   shell~> python -m pyshortcuts  my_script.py

?  That's kind of a guess, but I don't know how that would be better than the existing `pyshortcut` script that gets installed.

Please give a more concrete and complete example.

**Comment by lamaresh** [comment]
No sry, I mean it would be useful ti create a shortcut that executes a command like "python -m moduleName"

**Comment by newville** [comment]
@lamaresh  can't you just do that import in your script?

**Comment by newville** [comment]
@lamaresh ... but also ... did you try this and did it not work for you?  I think that it should work if you gave the full path to the python executable.

**Comment by lamaresh** [comment]
> @lamaresh ... but also ... did you try this and did it not work for you? I think that it should work if you gave the full path to the python executable.

Can I just add an argument after the executable? Moreover, the make_shortcut automatically add the path before the script, if i want to execute a module with the -m argument no path is needed before the module name. How can I achieve this result with the current make_shortcut function? 
Thank you for your help

**Comment by newville** [comment]
@lamaresh 

> Can I just add an argument after the executable? 

No.  

I should say that for some people, questions that start with "Can I just ...?" will often come across as sounding rather entitled.   That's not so much a helpful "how can we make the code do <something>?", it is more of an "I need your free tools to do <something>, you need to tell me how to do that".   For such a question, a plain "No" is remarkably polite.

> Moreover, the make_shortcut automatically add the path before the script, if i want to execute a module with the -m argument no path is needed before the module name. How can I achieve this result with the current make_shortcut function?

You can't.   The idea currently is that you are making a shortcut to a script, where you have complete control over what is imported and what resources are used as well as what code is run.

Closing.
