### ISSUE TITLE
Multiple icon resolution support (Windows)

### ISSUE THREAD

**Issue by kubinka0505** [newville/pyshortcuts#50]
<img src=https://user-images.githubusercontent.com/30776937/210643169-849e3e4c-ac8f-4a0b-855d-c117d7d5062f.png width=250 align=right>

As far as I know, Windows icons use ones embedded in the `DLL` or `EXE` files.

While using pyshortcuts I'm forced to use **static resolution of one image**, and it looks **very bad** in most cases, as shown.

Is there a workaround?
A possible solution to this:
1. Good
  - Accepting a list of paths to icons with different dimensions, (or one big, to rescale it and convert to image objects (i.e PIL)) and handling it to shortcut.
2. Ugly
  - Creating a `DLL` file (if it's possible - by some sort of developed wrapper) with rescaled icons. It could be created in the same directory each time that shortcut is made,

**Comment by newville** [comment]
@kubinka0505 
> As far as I know, Windows icons use ones embedded in the DLL or EXE files.

Icon images can be embedded in an executable file, but that makes it hard for any other program to be able to extract the images. I don't know how we would reliably extract such an image.

A windows shortcut can have only one icon file, but an icon file (".ico") can contain icons at multiple resolutions.  They usually do.

Without knowing more, I might suggest trying an icon file that actually contains multiple resolutions. 

I don't see how making a DLL just to hold an icon would help or what we would actually do with that file.   Do you have a concrete suggestion for this?

**Comment by kubinka0505** [comment]
> A windows shortcut can have only one icon file, but an icon file (".ico") can contain icons at multiple resolutions. They usually do.

😮 Interesting, going to check it out
<br>
>Do you have a concrete suggestion for this?
> > possible solution

Except above... none. ☹️

**Comment by kubinka0505** [comment]
I've generated multiple icons with GIMP, but it's still acting strange...
However, large icons option works now.

![obraz](https://user-images.githubusercontent.com/30776937/210655018-be5a8b12-920e-4fc4-80dd-e1cf75f43742.png)

**Comment by newville** [comment]
> I've generated multiple icons with GIMP, but it's still acting strange...

I don't know what "acting strange" means to you. 

> However, large icons option works now.
> Do you know what's the cause? Reassigning the icon with the explorer GUI option restores original quality...

The cause of what?   .... whatever it is, probably not.  I don't know that anything you are experiencing is a problem.

Pyshortcuts does not do anything with the icon files except pass them along to the shortcut file.  Icon files are actually a pretty standard thing (different but similar concept on macOS, but pretty much the same as they've been for a couple of decades on Windows and Linux).   There are many tools for making icon files and plenty of free icons are available.

**Comment by kubinka0505** [comment]
> I don't know what "acting strange" means to you.

Well, the image is pixelated on the left.

> Pyshortcuts does not do anything with the icon files except pass them along to the shortcut file.

Hmm. Maybe some used library side effect. Looks like I have to stick with what I have. 🙁
But least big icons work. 🙂

**Comment by newville** [comment]
@kubinka0505 

if you are using Gimp, you should be able to open the distributed `ladder.ico` file  (https://github.com/newville/pyshortcuts/blob/master/pyshortcuts/icons/ladder.ico) and see that it contains 6 images at different resolutions.   Again, that is a feature of an icon file.
