### ISSUE TITLE
Issues with shortcuts on Linux

### ISSUE THREAD

**Issue by Ahmed-E-86** [newville/pyshortcuts#51]
I used the python script to create a shortcut for my python application, and the final shortcut was like this:

```
[Desktop Entry]
Name=app_name
Type=Application
Path=/home/username
Comment=Here goes the application description.
Terminal=false
Icon=/home/username/app_folder/images/logo.ico
Exec=/usr/bin/python3
 /home/username/app_folder/main.py 
```
The application path is in another line, not in the same line as the python executable, and I have to remove that line manually to fix the shortcut.
Furthermore, the shortcut lacks one more thing that is vital for it to appear in the start menu, which is:
```
Categories=Utility;
```
There are a lot of categories to choose from, but `Utility` could be the default choice when nothing is defined.

The issue happens with Kubuntu 22.10, and Python 3.10.

Thank you for this amazing utility, and I hope this issue is fixed soon.

**Comment by newville** [comment]
@Ahmed-E-86 Hm, I don't have any idea why the "Exec" line would be split like that.  Can you send a script that runs `make_shortcut()` that would reproduce that?

For "Categories", see also the discussion at #23 - for the range of Linux desktops, I think the default category is not so obvious.   Still, I don't think anyone would be opposed to adding a "categories" entry.   It would be nice if there was a corresponding feature for Windows, describing where should this shortcut should go in the thing that acts like a Start Menu.  It would be even better if those were approximately the same syntax so that a single script running `make_shortcut()` worked correctly independent of OS.

**Comment by Ahmed-E-86** [comment]
I used the script like this:
```
from pyshortcuts import make_shortcut
import os.name

if os.name == 'posix'
  install_directory = os.path.join(os.path.expanduser('~'), 'app-name')
  icon = os.path.join(install_directory, 'images', 'logo.ico')
  app_executable = os.path.join(install_directory, 'main-tk.py')
  py_executable = os.popen('which python3').read()
  make_shortcut(app_executable, name='App Name', description='Application description goes here.', folder=None, icon=icon, terminal=False, desktop=True, startmenu=True, executable=py_executable)
```
Removing `executable=py_executable` from the python script fixed the issue, but it is still an issue for someone else, or if sys.executable returned an empty string.

**Comment by newville** [comment]
@Ahmed-E-86 Oh, well doing
> py_executable = os.popen('which python3').read()

the return value  of `popen(cmd).read()` will be lines with linebreaks.

But, that's also a Python script asking an OS shell what it thinks "python3" is.  In fairness, "which Python to use to run a script" does sometimes need a careful decision, but I would guess that using something other than `sys.executable` (the interpreter running the current script) would require some careful explanation.   

Having `sys.executable` be an empty string seems pretty strange.  How would that happen?

**Comment by Ahmed-E-86** [comment]
From what I know from searching previously on the internet, `sys.executable` is similar to `sys.argv`, it returns the current Python executable, so if I use a specific version of Python, or using virtual environment, later it will return nothing, so using `which python3` on Linux, and macOS will return the system-wide path of `python3`, which is more reliable.

`which` command does not work on Windows, but `where` command will work.

**Comment by newville** [comment]
@Ahmed-E-86 
> From what I know from searching previously on the internet, sys.executable is similar to sys.argv, it returns the current Python executable, 

I have no idea how you think that is similar to `sys.argv`.     See https://docs.python.org/3/library/sys.html#sys.executable

> so if I use a specific version of Python, or using virtual environment, later it will not work

I have never had `sys.executable` be an empty string, even with virtual environments.

> , so using which python3 on Linux will return the system-wide path of python3, 

`which python3` will return the full path of the first executable with that name using the current value of the PATH environmental value.   I cannot guess what `system-wide path` means to you.

> which is more reliable.

I do not agree.

> I know that /usr/bin/python3 and /bin/python3 are the standard on Linux, /usr/bin/python3, and /usr/bin/local/python3 are the standard on macOS, but I do not know what is the standard on Windows.

I don't actually see how any of that is relevant.   Whether or how one uses a "system provided" Python or a different environment has nothing to do with `pyshortcuts`.   

> While I enjoy Python so much, but when it comes to packaging, and creating a GUI, Python does not do well in these 2 points.

I have no idea what you are talking about.  

Anyway, you can make a shortcut with any executable you want.  But if you are going to use `os.popen(command).read()`, you really ought to understand that it will end with a newline. 

I don't see any issues related to `pyshortcuts` here.

**Comment by Ahmed-E-86** [comment]
I edited my previous comment briefly after posting it, and I admitted that I was wrong. Anyway, do you mind adding an example to your repo?

**Comment by newville** [comment]
Sorry, I don't understand: an example of what? 

It seems like the issue here is that `os.popen(command).read()` includes a newline.  That really has nothing to do with this library.  
One can specify an executable other than "current python".  I would not recommend using the shells `which` to do that,  but you can do it if you want.

**Comment by Ahmed-E-86** [comment]
> Sorry, I don't understand: an example of what?

I want to write an example that other users can use it on Windows, MacOS, and Linux, and put it inside the examples folder in your repo if you do not mind.

**Comment by newville** [comment]
@Ahmed-E-86 

An example of what?   

What would that example demonstrate that the existing one does not?

**Comment by Ahmed-E-86** [comment]
> @Ahmed-E-86
> 
> An example of what?
> 
> What would that example demonstrate that the existing one does not?

Nothing, forget that I asked.
