### ISSUE TITLE
Shortcuts when clicked disappear from Dock and not working for M1/M2 Mac Machines

### ISSUE THREAD

**Issue by justheretoclear** [newville/pyshortcuts#58]
Hi,

I have designed an app with Tkinter and I was using pyshortcuts library to create shortcuts at Desktop and Applications folders of Mac.
The shorctuts worked perfectly when I used Intel Mac Machine but they are not working when I am trying to create the at the M1 or M2 chip machines.

When I tried to access the contents folder of the app. The unix executable file inside MacOS folder is working correctly but these shortcuts when clicked are disappearing from the dock.

Below is the script which I used.

_**from re import sub
from pyshortcuts import make_shortcut
import subprocess
import TPLogger as lg

user = subprocess.getoutput('ls -l /dev/console | cut -d " " -f4')
ruta_user = f'/Users/{user}/Desktop'
ruta_app = f'/Applications'

make_shortcut('/opt/MyApp/MyAppScreen.py', name='MyApp', icon='/opt/MyApp/Resources/Images/MyApp.icns',terminal=True, folder=ruta_user)
make_shortcut('/opt/MyApp/MyAppScreen.py', name='MyApp', icon='/opt/MyApp/Resources/Images/MyApp.icns',terminal=True, folder=ruta_app)**_

Kindly suggest me some solution for the same. Thanks

Python version- 3.10

**Comment by newville** [comment]
@justheretoclear I guess it is not clear to me whether a Desktop shortcut is created or not. That would be expected. Are you also expecting the shortcut to automatically get added to the macOS Dock?   It should be possible to drag a shortcut to the Dock, but that won't happen automatically.

FWIW, this is a pure Python module.  I don't know how anything here could depend on the architecture.

**Comment by justheretoclear** [comment]
Hi @newville, Thanks for the reply.

The shortcuts getting created but its not working but when I try to use the unix executable at the path it works correctly.

Right click the Desktop shortcut->show contents->contents folder-> macOS-> myapp(Unix executable)

Don't know why the shortcut is not working though.

**Comment by justheretoclear** [comment]
The issue has been resolved. Thanks
